language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t scp0000/docker-fullstack-app -f ./frontend/Dockerfile.dev ./frontend
script:
  - docker run -e CI=true scp0000/docker-fullstack-app npm run test
after_success:
  - docker build -t scp0000/docker-frontend ./frontend
  - docker build -t scp0000/docker-backend ./backend
  - docker build -t scp0000/docker-nginx ./nginx
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
  - docker push scp0000/docker-frontend
  - docker push scp0000/docker-backend
  - docker push scp0000/docker-nginx
deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-fullstack-app"
  env: "Dockerfullstackapp-env"
  bucket_name: elasticbeanstalk-ap-northeast-2-082186817198
  bucket_path: "docker-fullstack-app"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY

